version: '3.8'
services:
  primbon-ajaib-frontend:
    image: primbon-ajaib-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ".:/build"
      - "./node_modules:/build/node_modules"
    stdin_open: true
    tty: true

networks:
  default:
    driver: bridge