version: '3.8'
services:
  primbon-ajaib-frontend:
    container_name: primbon-ajaib-frontend
    image: ghcr.io/avarian/primbon-ajaib-frontend:latest
    ports:
      - "${LISTEN_PORT:-8000}:80"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    driver: bridge